### PR TITLE
Add support for publishConfig.files

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Noticed this was missing

### CODE REVIEW

**Comment by bluwy** [comment]
Is there a package manager that uses `publishConfig.files` during packing? I tested npm, yarn1, yarn4, and pnpm, and all of them don't use that field. Only the root `files` field is used.

**Comment by bluwy** [comment]
I'll close this one for now

**Comment by NullVoxPopuli** [comment]
pnpm supports replacing everything on publish defined in publishConfig <3

**Comment by bluwy** [comment]
Not exactly? https://github.com/pnpm/pnpm/blob/f89128883fc5c4efb14f411a8878b9f771879b7e/pkg-manifest/exportable-manifest/src/overridePublishConfig.ts#L4-L27

**Pull request closed without merging**
