### PR TITLE
Add sidebar menu to rules page

### PR DESCRIPTION
**Pull request by btea**
image

### CODE REVIEW

**Comment by bluwy** [comment]
Thanks! I think this is a good idea, it could use a little design tweak so that the "Rules" content and the sidebar are centered on the screen. The sidebar could also get removed away on mobile, and I think it should be left un-ellipsis-truncated by default. The sidebar html could also be injected from the vite plugin instead: https://github.com/bluwy/publint/blob/1d24bf1599caa562dfb787abbd3ecba770b83916/site/scripts/vitePluginMarkdown.js#L58-L64

**Comment by btea** [comment]
@bluwy Done.

**Comment by bluwy** [comment]
Thanks! I polished it up more in the latest commit.

**Comment by btea** [comment]
Looks great! 👍

**Pull request merged**
