### PR TITLE
Improve site readability

### PR DESCRIPTION
**Pull request by Jungzl**

### CODE REVIEW

**Comment by bluwy** [comment]
Hi, can you show why this is needed? It was rendering fine for me before. What browser are you using? A before/after screenshot would be nice too.

**Comment by Jungzl** [comment]
OK, I'using Chrome & FF. 
The changes of code tag color are about contrast.
Before:
Snipaste_2023-02-13_09-37-16
Snipaste_2023-02-13_08-01-42
After:
Snipaste_2023-02-13_09-37-48
Snipaste_2023-02-13_09-22-20
And the changes of width is about word-breaking.(e.g. msw@1.0.1)
Before:
Snipaste_2023-02-13_09-23-00
After:
Snipaste_2023-02-13_09-23-11

**Comment by Jungzl** [comment]
Also, mobile devices have 'font boosting' image

**Comment by bluwy** [comment]
Ah thanks! I didn't test in light mode so I didn't catch that 🙏

**Review by bluwy — APPROVED** [review]

**Pull request merged**
